apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-test
  namespace: test
  labels:
    app: angular-test
spec:
  replicas: 1  # 👈 only one pod
  selector:
    matchLabels:
      app: angular-test
  template:
    metadata:
      labels:
        app: angular-test
    spec:
      containers:
        - name: angular-test
          image: registry.smolelab.com/angular-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred  # 👈 this should store your registry credentials
